---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/todos":
    get:
      summary: Lists todos
      tags:
      - Todo
      description: Lists todo
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    task:
                      type: string
                    done:
                      type: boolean
                    due_by:
                      type: date
                    created_at:
                      type: datetime
                    updated_at:
                      type: datetime
                    url:
                      type: string
                  example:
                    id: 1
                    task: Water plants
                    done: false
                    due_by: '2022-06-01'
                    created_at: '2022-06-01'
                    updated_at: '2022-06-01'
                    url: https://open-api-swagger.herokuapp.com/api/v1/todos/1.json
    post:
      summary: Creates a todo
      tags:
      - Todo
      description: Creates a new todo from provided data
      operationId: createTodo
      security:
      - JWT: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: success
          content:
            application/json:
              example:
                task: Water plants
                done: false
                due_by: '2022-06-01'
        '422':
          description: invalid request
          content:
            application/json:
              example:
                done: false
                due_by: '2022-06-01'
        '401':
          description: unauthorized request
          content:
            application/json:
              example:
                task: Water plants
                done: false
                due_by: '2022-06-01'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                done:
                  type: boolean
                  nullable: true
                due_by:
                  type: date
                  nullable: true
              example:
                task: Water plants
                done: false
                due_by: '2022-06-01'
              required:
              - task
              - done
              - due_by
  "/api/v1/todos/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Retrieves a todo
      tags:
      - Todo
      description: Retrieves a specific todo by id
      operationId: getTodo
      responses:
        '404':
          description: not found
        '200':
          description: success
          content:
            application/json:
              example:
                id: 1
                task: Water plants
                done: false
                due_by: '2022-06-01'
                created_at: '2022-06-01'
                updated_at: '2022-06-01'
                url: https://open-api-swagger.herokuapp.com/api/v1/todos/1.json
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  task:
                    type: string
                  done:
                    type: boolean
                  due_by:
                    type: date
                  created_at:
                    type: datetime
                  updated_at:
                    type: datetime
                  url:
                    type: string
    put:
      summary: Updates a todo
      tags:
      - Todo
      description: Updates a specific todo by id
      operationId: updateTodo
      security:
      - JWT: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                task: Water plants
                done: false
                due_by: '2022-06-01'
        '422':
          description: invalid request
        '401':
          description: unauthorized request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                done:
                  type: boolean
                due_by:
                  type: date
              example:
                task: Water plants
                done: false
                due_by: '2022-06-01'
    patch:
      summary: Updates a todo
      tags:
      - Todo
      description: Updates a specific todo by id
      operationId: patchTodo
      security:
      - JWT: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                done: false
        '422':
          description: invalid request
        '401':
          description: unauthorized request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                done:
                  type: boolean
                due_by:
                  type: date
              example:
                done: true
    delete:
      summary: Deletes a todo
      tags:
      - Todo
      description: Deletes a specific todo by id
      operationId: deleteTodo
      security:
      - JWT: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: success
  "/api/v1/todos?done={done}":
    get:
      summary: Lists completed or pending todos
      tags:
      - Todo
      description: Lists completed or pending todos
      parameters:
      - name: done
        in: path
        required: true
        schema:
          type: boolean
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    task:
                      type: string
                    done:
                      type: boolean
                    due_by:
                      type: date
                    created_at:
                      type: datetime
                    updated_at:
                      type: datetime
                    url:
                      type: string
                  example:
                    id: 1
                    task: Water plants
                    done: true
                    due_by: '2022-06-01'
                    created_at: '2022-06-01'
                    updated_at: '2022-06-01'
                    url: https://open-api-swagger.herokuapp.com/api/v1/todos/1.json
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: open-api-swagger.herokuapp.com
securityDefinitions:
  JWT:
    description: A jwt for API authorization
    type: apiKey
    name: Authorization
    in: header
